SirVer/ultisnips

- pythonx/UltiSnips/_vim.py
This fixes the following issue:
https://github.com/SirVer/ultisnips/issues/431
> Add support for vim's langnoremap new option

- doc/UltiSnips.txt
> Update document for zero tabstop.

- syntax/snippets.vim
This fixes #447.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/493)
> Fix folding for snippet files.

- pythonx/UltiSnips/_vim.py
This fixes Issue #540.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/541)
> Add field numbers to avoid errors in Python 2.6

- doc/UltiSnips.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/570)
> Fixed URL for Vimcasts in Documentation

- doc/UltiSnips.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/573)
> Fix Tabstops and Placeholders index

- README.md
The current link points to some other website.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/575)
> Fix link to Vimcasts

- autoload/UltiSnips.vim
- doc/UltiSnips.txt
- plugin/UltiSnips.vim
- pythonx/UltiSnips/snippet/source/_base.py
- pythonx/UltiSnips/snippet/source/_snippet_dictionary.py
- pythonx/UltiSnips/snippet_manager.py
- test/test_Autotrigger.py
- test/test_UltiSnipFunc.py
Merge back.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/582)
> autotrigger: make snippets expand without <tab>

- pythonx/UltiSnips/snippet/source/_base.py
- pythonx/UltiSnips/snippet/source/file/_base.py
- pythonx/UltiSnips/snippet_manager.py
fix #588
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/589)
> autotrigger: solve performance issues

- rplugin/python3/deoplete/sources/ultisnips.py
Deoplete is now stable. https://github.com/SirVer/ultisnips/issues/517
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/611)
> Add support for deoplete

- ChangeLog
- README.md
- doc/UltiSnips.txt
I made the documentation shorter and removed some fluff. I removed all uses of 'me' and mentioned the change of maintenance in appropriate places. Once this is merged I will do the 3.1 release and be on my way.
@seletskiy Could you have a look if you agree with everything in this PR?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/615)
> Updated changelog, readme and documentation for 3.1 and change of ownership.

- autoload/UltiSnips.vim
- doc/UltiSnips.txt
- pythonx/UltiSnips/snippet_manager.py
Add a function list all available snippets of current file.
The result is a list which also have location information, so that the snippet could be previewed in unite.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/625)
> add snippets_in_current_buffer function

- doc/UltiSnips.txt
Postfix snippets are an incredibly useful feature in IntelliJ IDE's.
Only recently I came to realize this [could be implemented with UltiSnippets](https://github.com/sniphpets/sniphpets-postfix-codes/blob/master/UltiSnips/php.snippets).
I think it would be a nice addition to the UltiSnippets documentation, in the hopes it could help others spend less time than I did trying to figure out how to put it together.
> Include examples about how to create postfix snippets

- pythonx/UltiSnips/_vim.py
> Use vim.bindeval() to avoid Unicode problems

- doc/UltiSnips.txt
> doc/UltiSnips.txt: Add ToC link to snippet options

- doc/UltiSnips.txt
To deal with space characters.
> Docs: alternative implementation of IsExpandable function

- doc/UltiSnips.txt
> Fix: the tag `UltiSnips-snippet-search-path` is obsolete

- pythonx/UltiSnips/snippet/definition/base.py
- pythonx/UltiSnips/snippet_manager.py
- pythonx/UltiSnips/vim_helper.py
Instead of accessing vim.current.window.cursor in some places.
> Use vim.buf.cursor abstraction everywhere

- autoload/UltiSnips.vim
- pythonx/UltiSnips/snippet_manager.py
This was broken in #1129 through a search & replaco. 
Fixes #1139.
> Fixes :UltiSnipsAddFiletypes no longer working as advertised

- pythonx/UltiSnips/snippet_manager.py
This relates to #1142 and the confusions users voice there.
> Show better error message if no directory for snippets is found.

- pythonx/UltiSnips/buffer_proxy.py
This removes a leftover print from commit https://github.com/SirVer/ultisnips/commit/aaa89bf0d62597f35b9d0de947c78f9539dadcd1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/1178)
> Remove unnecessary print

- pythonx/UltiSnips/snippet/parsing/base.py
- pythonx/UltiSnips/snippet/parsing/lexer.py
- pythonx/UltiSnips/snippet/parsing/ulti_snips.py
- pythonx/UltiSnips/text_objects/__init__.py
- pythonx/UltiSnips/text_objects/base.py
- pythonx/UltiSnips/text_objects/choices.py
- test/test_Choices.py
A sketchy implementation of Choices , releated #1166
> Feature: implement choices

- doc/UltiSnips.txt
an extra tag was placed, oops.
> Fix typo in doc

- syntax/snippets.vim
This PR enables spell checking inside comments.
> Enable spell checking in comments

- README.md
> Clearer wording on the YCM warning

- pythonx/UltiSnips/snippet/parsing/lexer.py
- pythonx/UltiSnips/text_objects/choices.py
- test/test_Choices.py
> Add support to escape comma inside choice item by "\,"

- pythonx/UltiSnips/snippet_manager.py
**This is draft pull request.**
I'm going to track related changes here and if it will work consistently in my setup for a while then it can be reviewed and merged.
Fixes #1157, Fixes #1141.
> autotrigger: trigger only on new characters insert

- test_all.py
> Test travis-ci.com integration.

- doc/UltiSnips.txt
- pythonx/UltiSnips/snippet/source/file/ulti_snips.py
- pythonx/UltiSnips/snippet_manager.py
Hi SirVer,
I refer to #1287 and hope this will fulfil your expectations.
Greetings
Jan
> add g:UltisnipsSnippetStorageDirectoryForUltiSnipsEdit

- doc/UltiSnips.txt
> Correct dead link in doc

- docker/run_tests.sh
- test_all.py
A low key attempt to understand the failures on CI.
> Fail tests on first failure on CI.

- README.md
- doc/UltiSnips.txt
[More info](https://github.com/jayli/vim-easycomplete#snippet-support)
> doc: vim-easycomplete supports ultisnips.

- pythonx/UltiSnips/snippet/definition/base.py
- pythonx/UltiSnips/snippet/source/file/base.py
- pythonx/UltiSnips/snippet/source/snippet_dictionary.py
- pythonx/UltiSnips/text_objects/python_code.py
- pythonx/UltiSnips/text_objects/snippet_instance.py
- test/test_ParseSnippets.py
Same as #1441 (I didn't know how to fix the git-mess I created there...)
This fixes #1428 and re-implements #1421. I went for the second approach described in https://github.com/SirVer/ultisnips/pull/1421#issuecomment-1027453551. I also added a test to check that global snippets can be used by snippets that are above them in the file. 
This also fixes the bug I mentioned in https://github.com/SirVer/ultisnips/pull/1421#issuecomment-1031259149 (the bug can be observed by running the new test on 3d78b73265b03b9abe25f223b3e7c9e083d79293)
> Fix precompile

- doc/UltiSnips.txt
> doc: explain how to (dis|en)able snipMate snippets

- test/test_ContextSnippets.py
- test/test_Fixes.py
- test/test_Interpolation.py
- test/vim_interface.py
- test_all.py
- Autodetects vim versions, but asserts that they are as expected
- not fail silently on issues with sending data to Vim.
Code by @mymedia2, superseeds #1474.
> Update test runner for more resilience

- test/vim_interface.py
It looks Vim 9.0 changed format output of `--version` and no longer prints applied extra patches on a separate line but joins the patch numbers with comma. As @jamessan rightly noted, the has_version method should check whether `patchlevel` is in set of listed patches.
And it is worth mentioning that the exact format is not documented and may change in future.
Fixes: #1514
> Check Vim version through call to Vim's has() function

- .github/workflows/main.yml
- Removes end of lifed python 3.7 and buster
- Adds Python 3.11
> Update CI run-matrix
