doc/UltiSnips.txt
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/text_objects/_base.py
pythonx/UltiSnips/text_objects/_snippet_instance.py
test/test_TabStop.py

Previously, adjacent tabstops like $1$2 were not handled properly.
$2 could be jumped to but no text could be added. See issue #457.

Fix adjacent tabstop input issue.

---

autoload/neocomplete/sources/ultisnips.vim

Hi,
I think "min_pattern_length", "max_candidates" and "is_volatile" are controlled by user setting.
So they are deleted.

Delete neocomplete.sources default setting

---

pythonx/UltiSnips/snippet_manager.py
test/test_Editing.py

Current behaviour is very annoying, when you want to undo snippet expansion and undo grabs a piece of your changes along with snippet.
Breaking undo achieved through re-setting &undolevel:
> Setting the value of 'undolevels' also breaks undo. Even when the new value is equal to the old value.
[:h :undoj]
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/486)

Add more precise undo levels (expanding, jumping)

---

doc/UltiSnips.txt
pythonx/UltiSnips/snippet/definition/_base.py
pythonx/UltiSnips/snippet/definition/snipmate.py
pythonx/UltiSnips/snippet/source/file/_base.py
pythonx/UltiSnips/snippet/source/file/ultisnips.py
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/text_objects/_snippet_instance.py
syntax/snippets.vim
test/test_ContextSnippets.py
test/test_UltiSnipFunc.py

Hello again!
This PR is a proof-of-concept of snippets, that can be expanded not only by matching prefix/regexp, but by context.
Consider this example:
```
if true {
}<TAB>
// becomes
if true {
} else {
}
// but
type MyType struct {
}<TAB>
// becomes
type MyData struct {
}
func (data MyData) SomeMethod() {
}
```
So, no matter that same trigger is used (`}` in that case), different snippets are chosen for expansion.
I think it's very powerful mechanism, which will lead to just hitting `<TAB>` in most cases without typing at all.
It's not ready-to-go solution, and I'm glad to listen some thoughts.
In current implementation snippets use following syntax:
```
snippet } "Description" "is_if_bracket(b, l, c)" xw
} else {
$1
}
endsnippet
```
Where `is_if_bracket` (note the `x` flag) is a python …

Context-aware snippets

---

ftdetect/UltiSnips.vim

I had a trouble with [kchmck/vim-coffee-script](https://github.com/kchmck/vim-coffee-script) that filetype detection auto commands are not defined within 'filetypedetect' augroup. After hours of debugging, I found it's a problem with UltiSnippet (and some other plugins).
From the [user guide](https://github.com/vim/vim/blob/master/runtime/doc/filetype.txt#L177-L185), autocommand in ftdetect scripts should not be surrounded with an augroup block.
During the startup of vim, ftdetect scripts are executed at the below line in `filetype.vim`.
https://github.com/vim/vim/blob/master/runtime/filetype.vim#L2713
You can find that ftdetect scripts are executed in 'filetypedetect' augroup, but `augroup END` can enclose 'filetypedetect' group unexpectedly, makes following auto commands (of plugins …

`augroup END` in ftdetect/UltiSnips.vim breaks other ftdetect scripts

---

pythonx/UltiSnips/_vim.py

This should be more performant.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/522)

VimBuffer: use vim.current.buffer.number instead of vim.eval

---

autoload/UltiSnips/bootstrap.vim
doc/UltiSnips.txt
pythonx/UltiSnips/__init__.py
pythonx/UltiSnips/_vim.py
pythonx/UltiSnips/buffer_helper.py
pythonx/UltiSnips/buffer_proxy.py
pythonx/UltiSnips/position.py
pythonx/UltiSnips/snippet/definition/_base.py
pythonx/UltiSnips/snippet/definition/snipmate.py
pythonx/UltiSnips/snippet/source/file/_common.py
pythonx/UltiSnips/snippet/source/file/ultisnips.py
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/text_objects/_base.py
pythonx/UltiSnips/text_objects/_python_code.py
pythonx/UltiSnips/text_objects/_snippet_instance.py
pythonx/UltiSnips/text_objects/_tabstop.py
syntax/snippets.vim
test/test_ContextSnippets.py
test/test_Editing.py
test/test_SnippetActions.py
test/test_TabStop.py
test/test_UltiSnipFunc.py
test/vim_test_case.py

Hi! It's me again.
I'm glad to introduce my shiny new PR, that introduces mechanism called "snippet actions". It makes possible to call arbitrary python code in certain snippet lifetime stages, like pre-expand, post-expand and post-jump.
I'd hope that help text is self-descriptive, so I will not repeat functionality description there.
**Note**: I've changed semantics of `cursor` value which is passed to previous mechanism "Context Snippets". After using it for a while I've found it highly inconvinient to use non-zero-based indexing for line numbers. I think there are not so many people who are use context snippets right now, so my change should not be devastating.
@SirVer: let's merge it fast. I have another productivity booster idea.
[<img src="https://reviewable.io/review_button.png" …

pre/post-expand and post-jump actions

---

doc/UltiSnips.txt

Was getting a "duplicate tag" error when running Helptags
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/537)

Pipe-quoting helptag reference to UltiSnips-context-snippets

---

pythonx/UltiSnips/snippet_manager.py

As recommended by the Vim help (`:h <nomodeline>`):
After applying the autocommands the modelines are
processed, so that their settings overrule the
settings from autocommands, like what happens when
editing a file. This is skipped when the <nomodeline>
argument is present. You probably want to use
<nomodeline> for events that are not used when loading
a buffer, such as |User|.
Fixes: https://github.com/SirVer/ultisnips/issues/542
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/544)

Use <nomodeline> when firing user autocmds

---

autoload/UltiSnips.vim

This is called via ftdetect/UltiSnips.vim, and needs to be defined
also if UltiSnips fails to initialize, e.g. because of missing Python
support.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/549)

Define UltiSnips#FileTypeChanged always

---

autoload/UltiSnips.vim
doc/UltiSnips.txt
plugin/UltiSnips.vim
pythonx/UltiSnips/snippet/source/_base.py
pythonx/UltiSnips/snippet/source/_snippet_dictionary.py
pythonx/UltiSnips/snippet_manager.py
test/test_Autotrigger.py
test/test_UltiSnipFunc.py

Guess what? It's me again.
This feature is a logical continuation of two preceding: context snippets and snippet actions.
Autotrigger combines them to achieve even faster programming style: there are
many places in a program code where only specific constructions can occurs.
E.g., in Go code on the top level you can see mostly (**p**)ackage / (**t**)ype / (**f**)unction / (**m**)ethod / (**v**)ar / (**c**)onst definition and nothing more.
So why use `p/t/f/m/v/c <TAB>` to expand snippet if one can use `p/t/f/m/v/c` alone which cause specific snippet to expand?
There are numerous applications for this feature, for example expanding operators in the middle of the code, e.g.
```
if (a =|)  ->  if (a == |)    automatically convert = to ==<SPACE>
```
I'm aware that it can be slow, I have some …

Autotrigger

---

pythonx/UltiSnips/snippet/definition/_base.py
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/text_objects/_python_code.py
test/test_ParseSnippets.py

When there is an error in executed python code inside snippet, it will print that code in the scratch buffer and mark the line where error has occured
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/592)

Show backtrace on error

---

pythonx/UltiSnips/buffer_proxy.py
test/test_SnippetActions.py

Last jump didn't work when post_expand action modifies char next to
snippet end.
Test `SnippetActions_PostActionModifiesCharAfterSnippet` will not pass on the current master.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/603)

fix last jump $0 placeholder using post_expand

---

autoload/unite/sources/ultisnips.vim

This is a cosmetic change. The trigger names are now aligned for the unite source. The screen shots show the before and after better than a description. 
Before:
After:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/608)

Enhancement: Align snippet names in unite source options

---

autoload/unite/sources/ultisnips.vim

Looks much better
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/624)

syntax highlight for unite ultisnips

---

syntax/snippets.vim

Consider the snippet
snippet test
${1:${VISUAL}}
endsnippet
A missing 'extend' keyword caused the inner closing bracket to end both
the inner 'snipVisual' and the outer 'snipTabStop' regions. Anything
after the inner bracket was considered 'snipSnippetBody' and thus
highlighted incorrectly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/628)

Fix highlighting for nested visual tabstob

---

rplugin/python3/deoplete/sources/ultisnips.py

I encountered an issue with Deoplete where Ultisnips suggestions wouldn't appear if there was a match in the current buffer with the same name as a Ultisnips snippet.  This change allows the snippet and buffer match to appear side-by-side, which is less confusing.
More information can be found on the issue on the Deoplete repo here:
https://github.com/Shougo/deoplete.nvim/issues/138#issuecomment-174050309

Allow Deoplete entries to show up with existing matches

---

doc/UltiSnips.txt
pythonx/UltiSnips/text_objects/_transformation.py
test/test_Transformation.py

As proposed, add re.MULTILINE flag to `TextObjectTransformation` class, it leads to an `m` option in transformations so also added respective documentation. tested with the following snippet:
```vim
snippet ul "make markdown unordered list from visual selection"
${VISUAL/^/* /mg}
endsnippet
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sirver/ultisnips/643)

Add support to do transformation on multiple lines

---

pythonx/UltiSnips/text_objects/_transformation.py
test/test_Transformation.py

check if the delimiters ```:```, ```(```, and ```)``` are actually escaped, not only if the previous char is a backslash
See https://github.com/SirVer/ultisnips/issues/656

Fix escapes in conditional tabstob transformation

---

autoload/UltiSnips.vim

Hi!  I created a plugin called [django-plus.vim][1] and would like UltiSnips to work with it since Django is an exceptional case in Vim.
The `django` filetype is considered a text template in Vim.  But, for users to easily enable the Django snippets in Python scripts, the `python.django` filetype can be used.  This causes some problems since plugins might not consider the dotted filetype, and filetypes like `markdown.django` or `yaml.django` (or even `python.django`) should actually be including `htmldjango.snippets`.
The other problem is that using `:UltisnipsEdit` without arguments, one would expect `django.snippets` to be loaded, but `python.snippets` is loaded instead.  The filetype would need to be `django.python`, but will break syntax highlighting in Python scripts. …

Add support for django-plus.vim

---

autoload/UltiSnips.vim

in `exec "xnoremap <silent> " . g:UltiSnipsExpandTrigger. " :call UltiSnips#SaveLastVisualSelection()<cr>gás"`
mapping to `:call` will actually execute `:'<,'>call`, which will call the function multiple times.  This will cause delay when visual contains many lines, and may have other unexpected behavior. so add the range argument

fix visual placeholder multi call

---

syntax/snippets.vim

This will allow snippets in subdirectories (e.g. [`snippets/coffee/*`](https://github.com/honza/vim-snippets/tree/master/snippets/coffee)) to have proper syntax highlighting.

syntax fix for subdirs

---

test/test_Autotrigger.py
test/test_Editing.py
test/vim_interface.py

has_patch(214) is meaningless if you don't pay attention to the
major/minor version: 7.4.214 != 8.0.214.

Fix Vim version checks in tests

---

doc/UltiSnips.txt

Emphasizing 'not' as `*not*` causes `:helptags` to generate a tag called
'not'. Because people like writing `*not*` in their documentations, this
can cause duplicate tag conflicts with other plugins (e.g. Command-T's
doc also generates a 'not' tag).

Fix emphasis in doc file that created a tag

---

pythonx/UltiSnips/vim_state.py

**This fix is for Windows only**
- Remove the last character in visual selection to fix the #863 issue.
- Fix typo in comment.

Fix selecting one more character when using ${VISUAL}.

---

pythonx/UltiSnips/text_objects/_visual.py
pythonx/UltiSnips/vim_state.py

The #864 fix (issue #863 ) causes selection problem when using multi-line selection.
- Fix the last character issue when using line selection mode (`V`) on Windows.

Fix selection when using ${VISUAL} in line selection mode on Windows.

---

rplugin/python3/deoplete/sources/ultisnips.py

As per https://github.com/Shougo/deoplete.nvim/pull/468#issuecomment-295168539 - UltiSnips suggestions depend on user input so the Deoplete source should be marked as `is_volatile`. Without this option Deoplete can cache an empty result from UltiSnips, causing no further snippets to be shown when the user input changes.

Mark Deoplete source as volatile

---

doc/UltiSnips.txt
doc/examples/autojump-if-empty/README.md

Currently, in the example [Autojump from tabstop when it's empty](https://github.com/SirVer/ultisnips/tree/master/doc/examples/autojump-if-empty), the text in the 1st tabstop and the 2 parentheses around it are removed unconditionally. I think they should only be removed if the user didn't insert anything.

don't clean 1st tabstop if it's not empty

---

pythonx/UltiSnips/text_objects/_visual.py

This fix is for windows users using selection `inclusive`. (Problem occurred since #868 )
> The pull request #883 is fine but missed the case when using `V` in `exclusive` mode.
> I planned to fix it after it being merged. But no one merged it because of the failing tests.
Issue #897 #921 and maybe #908 all refer to this problem, so I think it should be fixed as soon as possible.
However, `.travis.yml` seems to have some problem that make all tests fail.
The error message produced when testing using Travis CI:
It'll keep trying until the time is out.
W: The repository 'http://ppa.launchpad.net/kalakris/tmux/ubuntu trusty Release' does not have a Release file.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key …

Fix character selection when using VISUAL on all platforms

---

.travis.yml
Dockerfile

This will not help pull requests, as they are considered untrusted by Travis. But at least master builds and pull requests from branches in this repo should not hit rate limiting now.

Use a GitHub access token to avoid rate limiting of API.

---

pythonx/UltiSnips/err_to_scratch_buffer.py

There too many issues with traceback only. While it is good to have traceback, it is sell useful when it is the only info in the issue description. I think that contributing manual should be mentioned here even if we have issue template now. At least further new issues with traceback may follow contributing guide.

Add note about contributing to traceback

---

pythonx/UltiSnips/snippet_manager.py

If the user has a global mapping which begins like a local one, they probably expect the local mapping to win.
Without `<nowait>`, they would have to wait for the timeout to occur.

Prioritize local mappings over global ones

---

autoload/UltiSnips.vim
autoload/UltiSnips/map_keys.vim
autoload/neocomplete/sources/ultisnips.vim
autoload/unite/sources/ultisnips.vim

It prevents Vim from processing the rest of the statements inside a function, after having encountered an error.
It also gives shorter and more relevant stack traces in case of an error.

Give the `abort` argument to all Vim functions

---

pythonx/UltiSnips/_vim.py

This works around inconsistencies in Vim version about when and how
scratch buffers are generated and if the cursor jumps into them or not.

Fix test suite on Vim git version.

---

test/vim_interface.py

Patch detection failed on Vim 8.1, since it did not contain a '-'.

Make patch detection more resilient.

---

.travis.yml
Makefile
test/vim_test_case.py

After #1057 showed us that Python 3.7 changed something in the regex engine, it is time to test newer python versions independently.

Test python 3.6, 3.7 and 3.8.

---

pythonx/UltiSnips/test_diff.py
syntax/snippets_snipmate.vim
test/test_AnonymousExpansion.py
test/test_Autocommands.py
test/test_Chars.py
test/test_Completion.py
test/test_Editing.py
test/test_Expand.py
test/test_Fixes.py
test/test_Folding.py
test/test_Format.py
test/test_Interpolation.py
test/test_ListSnippets.py
test/test_Movement.py
test/test_MultipleMatches.py
test/test_Plugin.py
test/test_Recursive.py
test/test_Selection.py
test/test_SnipMate.py
test/test_SnippetOptions.py
test/test_SnippetPriorities.py
test/test_Transformation.py
test/test_UltiSnipFunc.py
test/vim_test_case.py
test_all.py

- I found the fold markers in the test subdirectories more annoying then useful.
- This also removes commented out code for interaction with YCM which will be unlikely to be resurrected anytime soon.

Remove dead code & fold markers.

---

rplugin/python3/deoplete/sources/ultisnips.py

Deoplete recently made a change that broke source base imports. See this commit in a repo by the author of deoplete that fixes the problem the same way I do here:
https://github.com/Shougo/neosnippet.vim/commit/23c97432929721af9130a163faa442dce76b1184

Fix deoplete source

---

Makefile

Choose python 3.6 as version for repro image

---

pythonx/UltiSnips/text_objects/python_code.py
test/test_Interpolation.py

When using snip.rv make sure it is interpreted as text.

---

doc/UltiSnips.txt
docker/docker_vimrc.vim
pythonx/UltiSnips/snippet/source/__init__.py
pythonx/UltiSnips/snippet/source/file/ulti_snips.py
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/vim_helper.py

This is a fairly breaking change.
- Removes `g:UltiSnipsSnippetsDir`.
- Simplifies logic around `:UltiSnipsEdit`: Without bang, it opens a snippet file in a subdirectory  of your `.vim` directory. The name of the sub directory will come from the members of `[gb]:UltiSnipsSnippetDirectories`. This will create a new snippet file and its enclosing directory if it does not yet exist (see below for details). With bang, it additionally adds all existing snippet files that are currently loaded for the current buffer.
- When the user needs to select a snippet file for editing, it shows a `*` for existing files.
Fixes #1120, #907 hopefully #711.
There are 4 combinations to be considered here: with or without bang and with `[gb]:UltiSnipsSnippetDirectories` containing a single absolute path or many …

Fundamentally changes how snippets are found.

---

pythonx/UltiSnips/vim_helper.py

Use $MYVIMRC as heuristic to find ~/.vim.

---

doc/examples/autojump-if-empty/README.md
doc/examples/snippets-aliasing/README.md

Hi!
Thank you for your amazing plugin!
I am new to it, and I was trying to learn how to use it from example files.
I took the code 'px.buffer.get().name' , but it was not working.
So I spent 2 hours searching why and, it was because the import px.snippets
was missing inside of this file.
So that's why I added it, I hope it can help other people.
Thank you for your time!

Added missing px.snippets import on example

---

pythonx/UltiSnips/snippet/source/file/snipmate.py
pythonx/UltiSnips/snippet/source/file/ulti_snips.py
pythonx/UltiSnips/vim_helper.py

If a user has created symlinks, we have no real reason to abstract back to the real inode path.
Side effect of this could be that the same snippet file shows up multiple times in `:UltiSnipsEdit`, but under different paths if symlinks are involved. This however feels like it is working as intended.
Fixes #1153.

Do not use realpath in most cases

---

pythonx/UltiSnips/snippet/source/file/common.py
pythonx/UltiSnips/snippet/source/file/snipmate.py
pythonx/UltiSnips/snippet/source/file/ulti_snips.py
pythonx/UltiSnips/vim_helper.py

This is a fix for a windows problem, but has semantic changes also for other platforms as `os.path.normpath` might change the meaning of a path that contains symbolic links.
Attempted fix for #1158.

Normalize all paths before returning them

---

pythonx/UltiSnips/vim_helper.py

Expand shell variables in MYVIMRC environment variable, because apparently Vim does it too.

Attempted fix for #1144.

---

pythonx/UltiSnips/vim_helper.py

Fixed unhandled KeyError when $MYVIMRC environment variable doesn't exist.

Update vim_helper.py to fix unhandled KeyError

---

pythonx/UltiSnips/snippet_manager.py

Currently, "SnippetManager._handle_failure()" receives the backward
trigger key instead of the list trigger key when listing fails
because there are no snippets for the current buffer.
If "g:UltiSnipsJumpBackwardTrigger" is set to, for example
"<S-Tab>", failing to list any snippets will send that key to the
type-ahead instead of the value of "g:UltiSnipsListSnippets".
In my Vim configuration, I have the following settings:
let g:UltiSnipsJumpBackwardTrigger = '<S-Tab>'
let g:UltiSnipsListSnippets = '<C-L>'
I get the following behavior before this commit:
1. Enter Insert mode
2. Press <C-L> to list snippets, listing fails b/c no snippets
3. A tab character is inserted when nothing should happen
This commit uses _handle_verify() properly so that no useless
characters are inserted into the …

Send the correct trigger key to _handle_failure()

---

.travis.yml
Makefile
pythonx/UltiSnips/snippet/source/file/ulti_snips.py

I think it is a good idea to re-establish the compatibility to
python 3.5, since it is widely used, e.g. in debian stretch.
`pathlib` in python 3.5 is missing some methods, like `startswith`.
In order to avoid using pathlib, the paths are cast to `str`.
See also here: https://bugs.python.org/issue27493
referencing #1201, #1190

Workaround for broken pre-3.6-pathlib

---

pythonx/UltiSnips/snippet_manager.py

This PR closes #1187 .
if user switches buffer while filling placeholder, exception is throwd and `_teardown_inner_state` does not set `False` to  `_inner_state_up`. so `_setup_inner_state` does not configure keyboard mappings.
I moved  `_inner_state_up = False` statement to `finally` block in `_teardown_inner_state`.
It guarantees `_inner_state_up` is set to `False` even if throws while processing tear down.

fix to JumpForwardTrigger works when snippets are used in two or more buffers

---

doc/examples/autojump-if-empty/README.md

'get_jumper_text' was not defined in autojump-if-empty example.
11009e6eb6570dd36f55e26d75326dfcb5f533ba introduce a check on the text but it was looking for a local function `get_jumper_text` instead of `px.snippets.get_jumper_text` function.
Fixes #1250

Fix: bug in autojump-if-empty example

---

pythonx/UltiSnips/err_to_scratch_buffer.py

Opening vim immediately fires a DeprecationWarning if python3.8 is used
and this behavior can be stopped by simply prefixing the string with `r`

Fix: DeprecationWarning from unescaped regex

---

pythonx/UltiSnips/text_objects/choices.py
test/test_Choices.py

Should fix the bug where you can't select the first one, when there are more than 9 candidates. 
Related [issue 1166 comment here](https://github.com/SirVer/ultisnips/issues/1166#issuecomment-662881641).

Optimize choices, support space as a terminator for selection

---

pythonx/UltiSnips/snippet/source/file/ulti_snips.py
pythonx/UltiSnips/snippet_manager.py

I found another case, where ultisnips crashed. Again it is because of
the incompatibility between pathlib and os.path in python v3.5.
The problem came, when there is no snippet file for the current file
type, cf. `snippet_manager.py`, line 98.
Instead of casting every `os.path` argument to str, I just avoided to
cast to `pathlib.Path` in the first place.
Also I added some type hints.

Python 3.5 Compatibility: Fix crash when snippet for current file does not exist 

---

ftplugin/snippets.vim

This PR makes editing tabstops in snippets easier esp. with the plugin, [vim-matchup](https://github.com/andymass/vim-matchup), which is a replacement of classic [matchit](http://ftp.vim.org/pub/vim/runtime/macros/matchit.txt).
```snippets
${1:fo|o} # "|" is cursor position.
```
then, `ci%`,
```snippets
${1:|}
```
Or,
```snippets                                                             
`!p snip.rv = b|ar`
```                                                                     
then, `ci%`,
```snippets                                                             
`!p |`                                                                  
```                                                                     
It seems undesirable to add `snip.rv` to `b:match_words` as a middle pattern of …

Improve b:match_words pattern

---

doc/examples/autojump-if-empty/README.md

1) Adding 'the' articles, where they are missing
2) Changing `<BS>` to <kbd>BackSpace</kbd> for consistency
3) Splitting into multiple sentences for easier reading

Enhancing the wording of an example

---

autoload/UltiSnips.vim
doc/UltiSnips.txt
pythonx/UltiSnips/snippet_manager.py
pythonx/UltiSnips/text_objects/snippet_instance.py

Closes #786.
Adds three functions, `UltiSnips#CanExpandSnippet`, `UltiSnips#CanJumpForwards`, and `UltiSnips#CanJumpBackwards`, which *significantly* cleans up more complex expansion functions.
The issue with the current method is that it requires we actually *run* the `<C-R>=UltiSnips#ExpandSnippet()<CR>` then check the result. This makes actually doing anything after it very difficult if you're in an `<expr>` mapping. Now we can have `<expr>` mappings that look like this: 
```lua
function expand_or_jump()
-- ...
if vim.api.nvim_eval([[ UltiSnips#CanExpandSnippet() ]]) == 1 then
return [[ <C-R>=UltiSnips#ExpandSnippet()<CR> ]]
end
-- ...
end
```
and etc.
Issue #786 was previously closed because it was said that `UltiSnips#SnippetsInCurrentScope()` has the same functionality, but it …

Added CanExpandSnippet, CanJumpForwards, CanJumpBackwards

---

.github/workflows/main.yml
test/vim_interface.py

Apparently, the new test runners are non-atomic in creating & writing to the done file. Since it contains the vim version that we expect to see this leads to us sometimes reading an empty string.
This fixes this race condition by having one version file (written first) and one done file where we do not care about the content.

Fix race condition in checking vim startup.

---

pythonx/UltiSnips/snippet/definition/snipmate.py
test/test_SnipMate.py
test_all.py

This seems to be the default for recent versions of snipMate in the wild, and we follow suite to retain compatibility.
Fixes #1325.

Expand snipMate snippets with 'i' option

---

autoload/unite/sources/ultisnips.vim

Fix #1337.
Unite defines a list of valid values for 'kind' in
`:help unite-kind-variables`. UltiSnips was using a custom one, but
doesn't seem to be adding a custom implementation for it. Instead, use
the default 'common' one. This allows
s:unite_source.action_table.expand.func to be called when the snippet is
invoked.
Test
Follow steps and minimal vimrc on issue #1337: invoke unite and expand
first snippet.

Use a valid unite kind variable

---

pythonx/UltiSnips/snippet/parsing/lexer.py
test/test_Expand.py

Correctly handle escaping backslashes in Placeholder defaults

---

pythonx/UltiSnips/snippet/definition/snipmate.py
test/test_SnipMate.py

This restores correct snipMate expansion behavior for esoteric snippets like `.` as trigger.
Fixes #1344, #1345

Expand snipMate snippets with 'w' instead of 'i'

---

docker/snippets/all.snippets
pythonx/UltiSnips/debug.py
pythonx/UltiSnips/diff.py
pythonx/UltiSnips/text_objects/snippet_instance.py
test/test_Mirror.py

This PR fixes the problem mentioned in issue #1339. _VimCursor dummy NoneditableTextObject is now created as a child of the EditableTextObject actually being edited at that time. Thereby it is ensured that it is unambiguous which mirrors should and should not move the cursor position further. It also resolves general issues when a snippet contains only tabstops and mirrors and no actual text.
Tests have been added to ensure that this remains functional and the test suite completes successfully.

Fix #1339 wrong cursor position in nested snippets

---

doc/UltiSnips.txt

When using a custom set of deoplete sources (as opposed to using everything) it can sometimes be hard to figure out *which* source you need to enable. Is it "us," "UltiSnips," "ultisnips," or something else entirely?
This PR adds the completion source name to the documentation to clear up any ambiguity, so that users don't have to dig through the source code.

Add deoplete completion source to the documentation

---

CONTRIBUTING.md
doc/UltiSnips-advanced.txt
doc/UltiSnips.txt
plugin/UltiSnips.vim
pythonx/UltiSnips/err_to_scratch_buffer.py
pythonx/UltiSnips/remote_pdb.py
test/vim_test_case.py
test_all.py

As discussed in #1403, and since you seemed enthusiast about it, I polished the remote debugger / post-mortem in something quite usable even though some stuff are still missing (like handling correctly arrow and completion keys...)
I am a bit sorry the code is somewhat messy, it was not that easy to make sure issuing a quit command would close the socket with vim resuming as if no debugger were launched, but at least, I tested it with pdb and pdb++ with all configuration possibility and it does what it is asked for, without altering UltiSnips when not enabled (I ran the test suite, and I have no fails).
Please don't ask me to provide a test case, I have truly no idea of how I would implement it =D

Added remote debug facilities (remote pdb server)

---

.github/workflows/main.yml

Official 3.5 support has ended in January and Python 3.10 is a thing now.

Remove Python 3.5 and add 3.10.

---

pythonx/UltiSnips/snippet/definition/base.py
pythonx/UltiSnips/text_objects/python_code.py
pythonx/UltiSnips/text_objects/snippet_instance.py

This commit changes the classes `SnippetDefinition` and `PythonCode` so that the code contained in Python interpolation, global snippets, snippet contexts and snippet actions is compiled (using Python's builtin `compile`) when an instance is created, instead of having `exec` compile the code every time it is executed.
This is (supposed to be) a non-functional change.
Compile times for Python code are very slow, e.g. compiling 63 lines of global snippets in my latex snippets file takes about 450 µs on my machine while executing the compiled code only takes 1.3 µs.

precompile python code in snippets

---

pythonx/UltiSnips/snippet/source/file/ulti_snips.py

Single wildcards ("*") are allowed in runtimepath entries, so expand them.
See `:h rtp<cr>71j` in Vim or `:h rtp-packages` in Neovim.

Handle wildcards in runtimepath entries. Fixes #1414.

---

doc/UltiSnips.txt
pythonx/UltiSnips/snippet/definition/base.py
test/test_ContextSnippets.py

As the title says. Actually more because `match` will also be available inside the scope of snippet actions.
I implemented it so that it is the same as the `match` variable exposed to the code in python interpolation. (There is a tiny contradiction to the documentation here, also for the match variable in python interpolation. When a snippet is not re triggered, `match` is `None` and not undefined as the docs suggest. This is probably fine.)
I can also add an example use case to the documentation.

Expose match object to python code in context conditions

---

pythonx/UltiSnips/snippet/definition/base.py
pythonx/UltiSnips/text_objects/python_code.py
pythonx/UltiSnips/text_objects/snippet_instance.py

The very cool feature of precompilation in #1421 introduced bug #1428, hence I felt the need to roll it back.
Fixes #1428.

Revert #1421 due to #1428.

---

doc/UltiSnips.txt

Also document that option `w` overrides option `i`. Fixes #1420.

document that regex snippets are expanded in-word

---

doc/UltiSnips.txt
pythonx/UltiSnips/snippet/definition/base.py
test/test_ContextSnippets.py

This would add a `before` attribute to the `snip` object in context conditions. `snip.before` should be equivalent to `snip.buffer[snip.line][:snip.column+1]`. **EDIT:** Actually, it's not because `vim.current.window.cursor` and by extension `snip.column` count bytes, not characters, see https://github.com/neovim/pynvim/issues/383.
However this implementation is faster on neovim (by ~ 0.7 ms) because it avoids an api call and the associated IPC overhead. An additional advantage is that it is more concise and avoids confusion about 1- and 0-based indexing.
If you decide you want to merge this I can write documentation for it.

expose text in line before snippet to context conditions (faster on neovim)

---

pythonx/UltiSnips/snippet/source/file/common.py
pythonx/UltiSnips/snippet_manager.py

Use realpath to get the actual path so symlink directories are counted
as equal and excluded from the set of output.
When dotfiles are symlinked:
> dir c:\users\idbrii\.vim
...
2020-12-08  04:01 PM    <SYMLINKD>     .vim [C:\dotfiles\vim]
`:UltiSnipsEdit!` outputs:
```
1: C:\Users\idbrii/.vim/bundle/david-snippets/UltiSnips/fugitive.snippets
* 2: c:\dotfiles\vim\bundle\david-snippets\ultisnips\all.snippets
* 3: c:\dotfiles\vim\bundle\david-snippets\ultisnips\all\shebang.snippets
* 4: c:\dotfiles\vim\bundle\snippets\ultisnips\all.snippets
* 5: c:\dotfiles\vim\bundle\project\ultisnips\all.snippets
* 6: c:\users\idbrii\.vim\bundle\david-snippets\ultisnips\all.snippets
* 7: c:\users\idbrii\.vim\bundle\david-snippets\ultisnips\all\shebang.snippets
8: c:\users\idbrii\.vim\ultisnips\all.snippets …
```

Resolve paths to avoid duplicates in UltiSnipsEdit

---

doc/UltiSnips.txt

Put all snippets examples in the documentation in `>` and `<` so vim help will format it literally. Closes #1292.
There are different variations in the styling, but all of them would require putting at least 1 space in front of each snippet line.

fix doc snippet formatting

---

pythonx/UltiSnips/snippet_manager.py
test/test_Fixes.py

Fixes #1184.
- if the trigger key does not expand a snippet, then pass it through
like a normal key
- if the expand/jump key use the same trigger, then the key will be
passed through if there is no expansion or jump
- added test cases

Pass through trigger key if no expansion done

---

syntax/snippets.vim

Excluding the double quote from match in `snipSnippetContextP` groups
can result in a wrong syntax highlight.
Therefore the ending `"` should be included in the syntax group.
Before:
After:

Fix snipSnippetContextP syntax to match the ending double quote

---

syntax/snippets.vim

The previous syntax group for snipGlobal was not matching and including
the endglobal keyword, resulting in a wrong folding region.
This commit fixes this, to make the endglobal keyword matched and
correctly included in the snipGlobal syntax region.
Note L18 `endglobal` is excluded and therefore not folded (with `foldmethod=syntax`).

Correct snipGlobal syntax regions

---

.github/workflows/main.yml

- Python 3.6 is end of lifed, so no longer run this.
- Adds Vim 9.0 which recently released.

Drop support for Py 3.6, also test Vim 9.0

---

pythonx/UltiSnips/snippet_manager.py

Setting the 'undolevels' option to any value has the side effect of creating an undo break.  UltiSnips uses the below construct to create an undo break with the goal of leaving 'undolevels' unmodified:
```
:let &undolevels = &undolevels
```
However, if a local 'undolevels' option has been set to a different value than the global option, the assignment above has the unintended effect of changing the global 'undolevels' value to the local value.
Use `&g:undolevels` to explicitly read and modify only the global option value, avoiding undesired option changes.
See the related pull request <https://github.com/vim/vim/pull/12729> suggesting related Vim documentation changes.
Currently, UltiSnips crashes on Neovim due in part to the issue described in this pull request: …

Avoid changing 'undolevels' when creating an undo break.

---

docker/run_tests.sh

With `pipefail`, the exit code for a pipeline will be taken from the first failing command in the pipeline, rather than the last command.

Mark failing CI tests as failed

---

docker/run_tests.sh
pythonx/UltiSnips/vim_helper.py
test/constant.py
test/test_Fixes.py

Both vim and neovim error out if we try to evaluate a string with a null byte in it. It appears that they use `<NL>` to represent `<Nul>` in several places, so replace any null bytes in text passed to `vim_helper.eval()` with newlines.
In my testing, I copied text from a file containing a null byte and pasted it into the commands that were giving errors, and found that the null byte does get treated as a word boundary in that case:
https://github.com/SirVer/ultisnips/blob/24a3ebb36687b6d59a19d63173713575b486d739/pythonx/UltiSnips/snippet/definition/base.py#L345-L347
https://github.com/SirVer/ultisnips/blob/24a3ebb36687b6d59a19d63173713575b486d739/pythonx/UltiSnips/snippet/definition/base.py#L388-L392
Fixes #1386.

Sanitize null bytes in eval'ed text

---

autoload/UltiSnips.vim
autoload/UltiSnips/map_keys.vim
doc/UltiSnips.txt
pythonx/UltiSnips/snippet_manager.py
test/test_Expand.py

This is a very small improvement. As far as I know, we can not consider to jump forward instead of expanding snippets first if the expand trigger is as same as the jump forward trigger. So I introduce two new options `g:UltiSnipsExpandOrJumpTrigger` & `g:UltiSnipsJumpOrExpandTrigger` to achieve this goal. If none of them is set, it'll still expand snippets first if two triggers remain same, or it'll map separately(that is, same as before, nothing broken).
Besides, I'm wondering how to write the document. I'll appreciate if some one could help me improve the document with adding the introduction of these two new options.
I'm not familiar with this project that I may misunderstand something or make some mistakes. If so, please let me know! Any advice is welcome. Hopefully my PR could be …

Add JumpOrExpand support

---

autoload/UltiSnips.vim
doc/UltiSnips.txt
pythonx/UltiSnips/snippet_manager.py
test/test_Autotrigger.py

~Now it is possible to disable AutoTrigger in the current buffer by setting the buffer variable `b:UltiSnipsAutoTrigger = 0`.~
Now it is possible to disable AutoTrigger via global variable `g:UltiSnipsAutoTrigger`, and to dynamically toggle AutoTrigger on/off with `Ultisnips#ToggleAutoTrigger()`.
This is just a first crude shot at implementing this "toggling feature" (documentation and so on TODO).
What do you think, is this alright, or is there perhaps some better way in your opinion?

Add variable to control AutoTrigger

---

autoload/UltiSnips.vim
plugin/UltiSnips.vim
pythonx/UltiSnips/snippet/source/base.py
pythonx/UltiSnips/snippet/source/file/base.py
pythonx/UltiSnips/snippet_manager.py

Ultisnips was traversing the whole runtimepath every time an expansion was attempted, something that happens for every key press since there is autotrigger.
Even without autotrigger, traversal was done at every snippet expansion, which caused slowdowns in that case.
With this change, traversal happens only the first time, or after a source must be refreshed (because a snippets file has been updated).
Note: I cannot run tests (Windows).

fix #1165: insert mode lag

---

docker/download_vim.sh

Fix "curl: (6) Could not resolve host: ftp.vim.org" when running tests.
This is the link on https://www.vim.org/download.php#unix on this line:
> There is one big file to download that contains almost everything. It
> is found in the unix directory
Looks like that change happened years ago to use https instead of ftp: https://github.com/vim/vim/issues/3580
Ran this script under Ubuntu on WSL:
```bash
VIM_VERSION=8.1
curl https://ftp.nluug.nl/pub/vim/unix/vim-${VIM_VERSION}.tar.bz2 -o vim.tar.bz2
tar xjf vim.tar.bz2
mv -v vim?? vim
ls vim/src/ | wc -l # outputs 255
```
I'm not **certain** it's the correct package, but it has source which seems comparable to cloning from git.

Switch from ftp.vim to ftp.nluug

---

.github/workflows/main.yml
Pipfile
docker/download_vim.sh
test/test_Autocommands.py
test/test_Choices.py
test/test_Interpolation.py
test/test_ParseSnippets.py
test/test_SnippetOptions.py
test/test_Transformation.py
test/test_UltiSnipFunc.py
test/vim_test_case.py

Also fix ci to be green again:
- Download VIM releases by tag from GitHub instead from FTP
- Fix several warnings about wrong escape sequences that Python >= 3.12 started to vomit on the screen.
- `assertRegexpMatches` is now called `assertRegex`.

Fix CI to be green again. Drop support for py3.8, py3.9 and Vim < 9.0

---

pythonx/UltiSnips/vim_helper.py

Fix #1041: iterating over snip.buffer fails in neovim.
Use __iter__() to defer iteration of a buffer to the underlying object.
Test
* Run this code in neovim and vim: import vim import UltiSnips.vim_helper as helper
```
def dump(b):
for line in b:
print(line.upper())
dump(vim.current.buffer)
dump(helper.VimBuffer())
```

Fix out of bounds NvimError: Add iter to VimBuffer
